version: "3.8"

networks:
  devnet:
    name: devnet
    driver: bridge

services:
  devbox:
    container_name: devbox
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GO_VERSION: "1.21.4"
        NODE_VERSION: "20.10.0"
        PHP_VERSION: "8.2"
        PYTHON_VERSION: "3.11"
        RUST_VERSION: "1.74.0"
    networks:
      - devnet
    volumes:
      - ../:/workspace
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ../..:/workspaces:cached
    entrypoint: /usr/local/share/docker-init.sh
    ports:
      - "8080:8080"
    command: sleep infinity
    # depends_on:
    #   - db
    #   - redis
